### ISSUE TITLE
Tuning the regularization parameters

### ISSUE THREAD

**Issue by suryadi-t** [i6092467/GVAR#1]
Hi,

In practical settings, when the true GC connections are unknown, how would you recommend the regularization parameters (both lambda and gamma) be tuned? In particular, using test (R)MSEs would probably not work well due to the issue raised in Appendix M.

Thank you for your time!
Suryadi

**Comment by i6092467** [comment]
Dear Suryadi,

The problem of selecting the right regularisation level, to the best of my knowledge, remains open in all of structure learning literature. As you pointed out correctly,  we observe that minimising MSE on the held-out data does not mean that the inferred time series structure corresponds to the ground truth.

In practice, I would suggest using something similar to the stability selection. For instance, you could split your time series into several (potentially overlapping) temporal sub-segments and fit a GVAR model on each of those. Then compare the inferred causal summary graphs across segments and quantify how similar/stable they are. Repeat steps above for a grid of hyperparameter values (both lambda and gamma) and select hyperparameter configuration which results in the most stable structure across subsamples. Of course, you will need to discard trivial cases, s.a. inferring a graph with the diagonal adjacency matrix or the full graph. 

Let me know if this suggestion makes sense to you. Feel free to contact me over email (ricards.marcinkevics@inf.ethz.ch) for a more detailed discussion.

Kind regards,
Ricards

**Comment by suryadi-t** [comment]
Hi Ricards,

Yes it does, thank you very much!
