### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by taka-precisionneuro** [i6092467/GVAR#2]
(base) ..\Network\GVAR> conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libpng==1.6.37=hbc83047_0
  - zstd==1.4.5=h9ceee32_0
  - libxcb==1.14=h7b6447c_0
  - sip==4.19.8=py37hf484d3e_0
  - lcms2==2.11=h396b838_0
  - glib==2.65.0=h3eb4bd4_0
  - intel-openmp==2019.4=243
  - numpy==1.18.5=py37ha1c710e_0
  - qt==5.9.7=h5867ecd_1
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - sqlite==3.32.3=h62c20be_0
  - libuuid==1.0.3=h1bed415_2
  - statsmodels==0.11.1=py37h7b6447c_0
  - tk==8.6.10=hbc83047_0
  - mkl_fft==1.1.0=py37h23d657b_0
  - dbus==1.13.16=hb2f20db_0
  - libtiff==4.1.0=h2733197_1
  - ld_impl_linux-64==2.33.1=h53a641e_7
  - expat==2.2.9=he6710b0_2
  - pillow==7.2.0=py37hb39fc2d_0
  - mkl-service==2.3.0=py37he904b0f_0
  - zlib==1.2.11=h7b6447c_3
  - ninja==1.9.0=py37hfd86e86_0
  - readline==8.0=h7b6447c_0
  - lz4-c==1.9.2=he6710b0_1
  - pcre==8.44=he6710b0_0
  - freetype==2.10.2=h5ab3b9f_0
  - numpy-base==1.18.5=py37hde5b4d6_0
  - matplotlib-base==3.2.1=py37hef1b27d_0
  - libffi==3.3=he6710b0_1
  - jpeg==9b=h024ee3a_2
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - python==3.7.7=hcff3b4d_5
  - openssl==1.1.1g=h7b6447c_0
  - tornado==6.0.4=py37h7b6447c_1
  - libgcc-ng==9.1.0=hdf63c60_0
  - scikit-learn==0.22.1=py37hd81dba3_0
  - mkl==2019.4=243
  - pandas==1.0.5=py37h0573a6f_0
  - kiwisolver==1.2.0=py37hfd86e86_0
  - cudatoolkit==10.1.243=h6bb024c_0
  - libxml2==2.9.10=he19cac6_1
  - xz==5.2.5=h7b6447c_0
  - libedit==3.1.20191231=h7b6447c_0
  - pyqt==5.9.2=py37h05f1152_2
  - gstreamer==1.14.0=hb31296c_0
  - libgfortran-ng==7.3.0=hdf63c60_0
  - pytorch==1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - fontconfig==2.13.0=h9420a91_0
  - cffi==1.14.0=py37he30daa8_1
  - scipy==1.5.0=py37h0b6359f_0
  - mkl_random==1.0.4=py37hd81dba3_0
  - ncurses==6.2=he6710b0_1
  - icu==58.2=he6710b0_3

**Comment by i6092467** [comment]
Please try with an updated environment.yml file (pushed to the repo just now). Please let me know if you have further issues.

**Comment by taka-precisionneuro** [comment]
Thank you for your quick reply. but still getting the following: 

ResolvePackageNotFound:
  - libgcc-ng=9.1.0
  - gstreamer=1.14.0
  - ncurses=6.2
  - readline=8.0
  - scs=2.0.2
  - ld_impl_linux-64=2.33.1
  - libgfortran-ng=7.3.0
  - libedit=3.1.20191231
  - libstdcxx-ng=9.1.0
  - gst-plugins-base=1.14.0
  - libxcb=1.14
  - libuuid=1.0.3
  - dbus=1.13.16

**Comment by i6092467** [comment]
Looking closer at it, it seems you are running Windows. Some of these libraries are available for Linux only (you can look them up at [https://anaconda.org/search](https://anaconda.org/search)). I suggest either running the code on a Linux machine or manually removing Linux-only libraries from your local environment.yml file and trying to see if the code runs w/o them.
