### ISSUE TITLE
Direction of causal matrix

### ISSUE THREAD

**Issue by cloudy-sfu** [i6092467/GVAR#4]
Your logged causal matrix in CSV file seems to have different direction from Figure 2 in published paper.

Entreis `(i, j)` in logged causal matrix (result of `run_grid_search` function) means `i causes j` or `j causes i`?

**Comment by i6092467** [comment]
Hello. Figure 2 in the paper serves a purely conceptual purpose. 

The causal matrix from the `run_grid_search` function corresponds to the adjacency matrix of the GC summary graph, i.e. nonzero entry `(i, j)` means "`i` causes `j`"

**Comment by cloudy-sfu** [comment]
Helpful. Thank you!
